### PR TITLE
Add full stop

### PR DESCRIPTION
**Pull request by thortol**
## Describe your changes
no need to explain
## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by KiKuasaurus — APPROVED** [review]
LGTM!

**Review by jevan13 — APPROVED** [review]
LGTM!

**Review by InfinityTwo — APPROVED** [review]
LGTM

**Review by LimErnest — APPROVED** [review]
LTGM! Looks TOO GOOD to Me

**Pull request merged**
