### PR TITLE
Fix UG bugfixes

### PR DESCRIPTION
**Pull request by InfinityTwo**
## Issue ticket number and link
Builds on #140 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by thortol** [comment]
my disappointment is immeasurable and my day is ruined

**Comment by LimErnest** [comment]
How is it possible for you to merge without any reviews?

**Comment by KiKuasaurus** [comment]
It is important to make sure that all code is properly reviewed. This will be in the next post-mortem review.

**Comment by jevan13** [comment]
I do not remember approving this.

**Pull request merged**
